apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-activity-api
spec:
  selector:
    matchLabels:
      app: user-activity-api
  replicas: 2
  template:
    metadata:
      labels:
        app: user-activity-api
    spec:
      containers:
        - name: user-activity-api
          image: abdelrahmanelbadawy1/user-activity-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/user-activities"
            - name: KAFKA_BROKERS
              value: "kafka:9092"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-activity-api
spec:
  selector:
    app: user-activity-api
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
